create database lancamentos_db;
use lancamentos_db;

-- Tabela de categorias
CREATE TABLE categorias(   id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY ,  descricao VARCHAR(255) NOT NULL) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


-- Tabela de estados
CREATE TABLE estados( sigla VARCHAR(2) NOT NULL PRIMARY KEY , nome VARCHAR(100) NOT NULL) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


-- Tabela de cidades
CREATE TABLE cidades( id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(255) NOT NULL, estado_sigla VARCHAR(2) NOT NULL, 
CONSTRAINT fk_cidade_estados1 FOREIGN KEY (estado_sigla) REFERENCES estados (sigla) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- Tabela de pessoas
CREATE TABLE pessoas (id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,  nome VARCHAR(255) NOT NULL, ativo TINYINT(4) NOT NULL) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- Tabela de contatos
CREATE TABLE contatos( id BIGINT(20) NOT NULL AUTO_INCREMENT primary key, nome VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefone VARCHAR(14) NOT NULL,
  pessoa_id BIGINT(20) NOT NULL, CONSTRAINT fk_contatos_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoas (id) ON DELETE CASCADE ON UPDATE NO ACTION)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Tabela de enderecos
CREATE TABLE enderecos(  pessoa_id BIGINT(20) NOT NULL, logradouro VARCHAR(255) NOT NULL, numero VARCHAR(45) NOT NULL, complemento VARCHAR(255) NOT NULL,
  bairro VARCHAR(45) NOT NULL, cep VARCHAR(10) NOT NULL, cidade_id BIGINT(20) NOT NULL, CONSTRAINT fk_endereco_cidade1  FOREIGN KEY (cidade_id)  REFERENCES cidades (id) 
    ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT fk_endereco_pessoas1 FOREIGN KEY (pessoa_id)   REFERENCES pessoas (id) ON DELETE NO ACTION ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- Tabela de lancamentos
CREATE TABLE lancamentos( id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, descricao VARCHAR(255) NOT NULL,dt_vencimento DATE NOT NULL,dt_pagamento DATE NULL DEFAULT NULL,
valor DECIMAL(10,2) NOT NULL,observacao TEXT NULL DEFAULT NULL, tipo ENUM('RECEITA', 'DESPESA') NOT NULL,pessoa_id BIGINT(20) NOT NULL,categoria_id BIGINT(20) NOT NULL,
CONSTRAINT fk_lancamento_pessoa1 FOREIGN KEY (pessoa_id) REFERENCES pessoas (id) ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT fk_lancamentos_categorias1
    FOREIGN KEY (categoria_id) REFERENCES categorias (id) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;
